# This rule is not used by the project route itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the route.multi.ch.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: route
    app.kubernetes.io/managed-by: kustomize
  name: route-editor-role
rules:
- apiGroups:
  - route.multi.ch
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.multi.ch
  resources:
  - routes/status
  verbs:
  - get
