---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-route-multi-ch-v1-route
  failurePolicy: Fail
  name: mroute-v1.kb.io
  rules:
  - apiGroups:
    - route.multi.ch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - routes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-route-multi-ch-v1-route
  failurePolicy: Fail
  name: vroute-v1.kb.io
  rules:
  - apiGroups:
    - route.multi.ch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - routes
  sideEffects: None
