# This rule is not used by the project app itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over app.multi.ch.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/managed-by: kustomize
  name: app-admin-role
rules:
- apiGroups:
  - app.multi.ch
  resources:
  - apps
  verbs:
  - '*'
- apiGroups:
  - app.multi.ch
  resources:
  - apps/status
  verbs:
  - get
