---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - maintenance.multi.ch
  resources:
  - maintenances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maintenance.multi.ch
  resources:
  - maintenances/finalizers
  verbs:
  - update
- apiGroups:
  - maintenance.multi.ch
  resources:
  - maintenances/status
  verbs:
  - get
  - patch
  - update
